name: resolve
description: Managing dependencies with simple Widgets.
version: 0.2.0
author: Alo√Øs Deniel<alois.deniel@gmail.com>
homepage: https://github.com/aloisdeniel/flutter_resolve
environment:
  sdk: ">=2.1.0-dev <3.0.0"

dependencies: 
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_test:
    sdk: flutter
  test: "^1.3.3" 